version: '3.3'
services: 
    db:
        image: postgres
        volumes:
            - db:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - "5432:5432"

    funbits:
        image: funbits-server
        depends_on:
            - db
        environment:
            DATABASE_URL: db://funuser:password@db:5432/funbits
        ports:
            - "4000:4000"
volumes:
    db: